name: Deploy to Hostinger VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      VM_IP: ${{ secrets.VM_IP }}
      SSH_USER: ${{ secrets.SSH_USER }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Add SSH Key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add VM to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan ${{ env.VM_IP }} >> ~/.ssh/known_hosts

      - name: Create directory on VM
        run: |
          ssh -o StrictHostKeyChecking=no ${{ env.SSH_USER }}@${{ env.VM_IP }} "
          mkdir -p /home/${{ env.SSH_USER }}/git_code_realestate"

      - name: Copy files to VM
        run: |
          rsync -avz -e "ssh -o StrictHostKeyChecking=no" . ${{ env.SSH_USER }}@${{ env.VM_IP }}:/home/${{ env.SSH_USER }}/git_code_realestate

      - name: Run setup script on VM
        run: |
          ssh -o StrictHostKeyChecking=no ${{ env.SSH_USER }}@${{ env.VM_IP }} "
          echo 'Running setup script...'
          sudo sh /home/${{ env.SSH_USER }}/git_code_realestate/devops_scripts/setup.sh"

      - name: Run deployment script on VM
        run: |
          ssh -o StrictHostKeyChecking=no ${{ env.SSH_USER }}@${{ env.VM_IP }} "
          echo 'Running deployment script...'
          sudo sh /home/${{ env.SSH_USER }}/git_code_realestate/devops_scripts/deploy.sh"